// <auto-generated />
namespace NoChangeParking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class VerifyPaymentsremovespaces : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VerifyPaymentsremovespaces));
        
        string IMigrationMetadata.Id
        {
            get { return "201511191743547_Verify-Payments-remove-spaces"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
