// <auto-generated />
namespace NoChangeParking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addstatustoverifypayment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addstatustoverifypayment));
        
        string IMigrationMetadata.Id
        {
            get { return "201511181759372_Add-status-to-verify-payment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
